apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: client
  name: client
spec:
  containers:
    - env:
        - name: GET_HOSTS_FROM
          value: dns
      image: lukondefmwila/dkr-multicontainer-app-client
      name: client
      resources: {}
  restartPolicy: OnFailure
status: {}
